### PR TITLE
Events

### LINKED ISSUE #4: add event-card.tsx
depends on https://github.com/Spartan-Disability-Alliance/website/issues/7

### LINKED ISSUE #11: add upcoming-events.tsx
depends on https://github.com/Spartan-Disability-Alliance/website/issues/4

### LINKED ISSUE #12: add past-events.tsx
depends on #4

### LINKED ISSUE #17: add events
depends on #11, #12

### PR DESCRIPTION
**Pull request by trungtran1234**
Closes #11 
Closes #12 
Closes #17 
Closes #4 

Desktop View with Empty Upcoming Events
Screenshot 2024-10-10 213743
Desktop View with Optional Image and Non-Empty Upcoming Events
Screenshot 2024-10-10 210447
Mobile View:
Screenshot 2024-10-10 205317

### CODE REVIEW

**Review by raspberri05 — CHANGES_REQUESTED** [review]
it it possible for it to be so that for upcoming events, if there is an upcoming event, it still shows as a full length card instead of half length. this just draws more attention to the upcoming events rather than the card being the same width as in past events

**Comment by raspberri05** [comment]
also could the text for the no upcoming events card say "No upcoming events. Check back for updates!" pls

**Review by raspberri05 — APPROVED** [review]
lgtm!

**Comment by trungtran1234** [comment]
Changed upcoming events to full card:
Screenshot 2024-10-10 223401

**Pull request merged**
